name: Run test cases

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo hi
